### ISSUE TITLE
No Imports

### ISSUE THREAD

**Issue by sentania** [cderickson/MTGO-Tracker#2]
I'm trying to import gamelogs but it's not working.  Logs are present.

Config:
![image](https://user-images.githubusercontent.com/2688043/163513491-bc16169b-26a7-4a6a-ba2d-119fa632f863.png)

Logs are present:
![image](https://user-images.githubusercontent.com/2688043/163513542-cee66d9f-4d18-4991-9e43-6eba4449c8c5.png)

Logs don't upload/get imported

Are there any logs I can upload?  It appears game logs are copied to the gamelogs directory where I extracted the app, but the tracker reports:
![image](https://user-images.githubusercontent.com/2688043/163513956-5f9a28f8-b14b-4c73-89aa-7cbc46df7fa8.png)

**Comment by sentania** [comment]
![image](https://user-images.githubusercontent.com/2688043/163513982-cb118542-9335-4f1d-b51a-b5eb258d3167.png)

**Comment by sentania** [comment]
It seems like once I closed MTGO and reimported all was good.  MTGO being open appears to lock something

**Comment by cderickson** [comment]
Interesting, even though you seem to have solved your own problem, thanks for letting me know. I didn't know having MTGO running would cause any issues.

If you have any issues in the future, attaching a zip file with your /gamelogs/ folder, or the entire /2.0/ folder (~700mb) would help me with debugging.
