### ISSUE TITLE
"Format" Column Autofills as NA with no obvious way to guess format automatically

### ISSUE THREAD

**Issue by azax1** [cderickson/MTGO-Tracker#20]
The Getting Started page says Data Cleaning addresses this, but the Data Cleaning page is seemingly silent on format.

https://github.com/cderickson/MTGO-Tracker/wiki/Getting-Started
https://github.com/cderickson/MTGO-Tracker/wiki/Data-Cleaning-Methods

**Comment by cderickson** [comment]
Match Format is not able to be derived from the GameLog files, so this column has to filled manually with the Revise Record(s) button on the left hand side.

I'll update the Readme/Wiki to make this more clear.
