### ISSUE TITLE
0 imported matches

### ISSUE THREAD

**Issue by szkuznik** [cderickson/MTGO-Tracker#22]
Hello I would love to use this program, I tried to follow your instuctions:
![image](https://github.com/cderickson/MTGO-Tracker/assets/61904253/5b77c7ed-db99-4bce-a118-f60bb28d6f7f)
![image](https://github.com/cderickson/MTGO-Tracker/assets/61904253/47cd6c8e-d4eb-4896-9d59-9d8414ea7d28)

I played a lot of games on mtgo, so there should be some logs:
![image](https://github.com/cderickson/MTGO-Tracker/assets/61904253/00331469-047e-4588-a12d-18a1ccf9866b)
Am I missing something?

**Comment by cderickson** [comment]
Were any files copied over to your gamelogs or draftlogs folder? If there are any, can you please zip these files and attach those here along with the DEBUG.txt file so I can diagnose?

**Comment by szkuznik** [comment]
@cderickson Folders are empty, ataching debug file
[DEBUG.txt](https://github.com/cderickson/MTGO-Tracker/files/11950624/DEBUG.txt)

**Comment by cderickson** [comment]
Yeah it looks like it just didn't find any GameLog files to scan. Did you recently re-install MTGO or Windows? Are you clicking 'Scan for New Files, not Re-Import Copies?

You can try going through those folders and making sure there are GameLog files that exist (this is what they look like):

![image](https://github.com/cderickson/MTGO-Tracker/assets/17014141/ef0c861c-7180-42e1-9de6-eff1d405abfc)

You could also zip your /2.0/ folder and try attaching it here, or emailing to me, or uploading it somewhere I can download so I can try to see what's going on on my machine. It might be kind a large file though.
