### ISSUE TITLE
Additional Archetypes

### ISSUE THREAD

**Issue by jfww** [cderickson/MTGO-Tracker#25]
Hey, really appreciate this program existing, it's made playing MTGO a lot more fun for me!

Would it be possible to enable the addition of additional archetypes to the drop down menu? Or at the very least adding "graveyard" as an archetype, since I feel like combo doesn't quite capture decks like dredge or reanimator.

**Comment by cderickson** [comment]
![Capture](https://github.com/cderickson/MTGO-Tracker/assets/17014141/00c5b0c9-479d-4928-9c44-aaa99f9f97fb)
Thanks I'm glad you are enjoying using the tool :)

There is already the ability to add new or custom archetypes to the dropdown menu by revising the INPUT_OPTIONS.txt file. Simply add 'Graveyard' or any other archetype under the appropriate header on a new line.

Let me know if you have any other questions/clarifications

**Comment by jfww** [comment]
That's great, thank you!
