### ISSUE TITLE
Combining two deck names that refer to the same deck

### ISSUE THREAD

**Issue by twinlesstwinmtg** [cderickson/MTGO-Tracker#26]
Hi, I am having an issue where my Murktide deck is referred to as UR Murktide some of the time and UR tempo the other half of the time. Is there a way to efficiently combine these?

**Comment by cderickson** [comment]
There's no automated way to combine these unfortunately. I would sort the table by deck name so you can multi-select a bunch of your matches vs UR X decks and manually apply a new deck name in one operation to save some time.

The deck names are scraped from MTGGoldfish and aren't standardized, and matches where few cards were played are also less likely to be accurate.

**Comment by twinlesstwinmtg** [comment]
How do you multi-select and manually apply a name in one operation? I’m happy to do that just don’t want to click everything one at a time On Sep 7, 2023, at 9:46 PM, Chris Erickson ***@***.***> wrote:﻿
There's no automated way to combine these unfortunately. I would sort the table by deck name so you can multi-select a bunch of your matches vs UR X decks and manually apply a new deck name in one operation to save some time.
The deck names are scraped from MTGGoldfish and aren't standardized, and matches where few cards were played are also less likely to be accurate.

**Comment by cderickson** [comment]
You can use shift-click to highlight everything in between two rows. For example, highlight the top row, then shift-click on the bottom row will highlight every row.
