### ISSUE TITLE
Unable to import matches. Found fix?

### ISSUE THREAD

**Issue by mikael2123** [cderickson/MTGO-Tracker#28]
I tried to import my matches. It did not work. I followed [this reddit link ](https://www.reddit.com/r/MTGO/comments/st9x4p/mtgotracker_match_historystats_tool_for_mtgo/hx5sbzw/) and copied the folder locations in the image exactly (obviously, I replaced 'chris' with my User). It still didn't work. 

So, I figured since this was python, maybe I could figure it out myself even though I am not a programmer since python is very readable. So I download the source code zip (I only realized after writing this post that there have been a lot of changes since the version 15 I downloaded. To be clear, I downloaded the v15 source zip on the releases page, not the current version with all the recent changes) and ran the python file, do the same steps and finally I can see a python error that I can work with.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Mikael\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Mikael\Desktop\qqqqqqqqqqMTGO-Tracker-v.15\MTGO-Tracker-v.15\mtgo_tracker.py", line 2969, in <lambda>
    button3 = tk.Button(bot_frame,text="Scan for New Files",width=15,command=lambda : import_data(overwrite=False))
                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikael\Desktop\qqqqqqqqqqMTGO-Tracker-v.15\MTGO-Tracker-v.15\mtgo_tracker.py", line 2940, in import_data
    get_all_data(fp_logs=FILEPATH_LOGS,fp_drafts=FILEPATH_DRAFTS,copy=True)
  File "C:\Users\Mikael\Desktop\qqqqqqqqqqMTGO-Tracker-v.15\MTGO-Tracker-v.15\mtgo_tracker.py", line 663, in get_all_data
    initial = gamelog.read()
              ^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
```

(Program folder is qqqqqqqqqqMTGO-Tracker-v.15 so I don't confuse it with the prebuilt version I downloaded earlier) So I search the "UnicodeDecodeError: 'mbcs' codec can..." in google and find [this reddit post](https://www.reddit.com/r/learnpython/comments/cv8dvv/unicodeencodeerror_mbcs_codec_cant_encode/) which says to change to change the encoding to "latin1". After I change the encoding from "ansi" to "latin1" in line 662 (in the current version it seems to be line 678), it just works. 

Again, I am not a programmer, I just know that this program now properly imports my matches. If I had to guess why it doesn't work on my system, I have a couple of guesses. First and what I think is most likely, is that my system locale is set to Japanese in order to play various Japanese games that require that setting. Second, perhaps the new Lorien Revealed card and it's accent on the 'o' messes up the program? Those are my two guesses. This is an issue and not a pull request (is that what they're called?) because I do not even know what "latin1" is and what it is used for or if there is a better encoding or anything of the sort. If I should've posted it somewhere else, please tell me for the future.

**Comment by cderickson** [comment]
Interesting bug find, thanks for doing a lot of the legwork in fixing it for me :)

Would you mind uploading a zip file of your **/gamelogs** folder so I try importing on my system? Then I can see which cards/characters the parser is having trouble reading, or if the issue is with your system locale.

**Comment by mikael2123** [comment]
Sure, here's the file. [gamelogs.zip](https://github.com/cderickson/MTGO-Tracker/files/12787915/gamelogs.zip)

**Comment by cderickson** [comment]
Yeah, it imports fine on my machine (although accented characters are recorded differently like you noted), so it must be an issue with how ansi encoding is interesting with your system locale.

I'll test out latin1 encoding and possible include in the next release.

Thanks for your help, and let me know if you run into any other issues or have any questions

**Comment by cderickson** [comment]
Latin1 encoding implemented with latest release 16.
