### ISSUE TITLE
Statistics Data window is blank

### ISSUE THREAD

**Issue by derekwong9** [cderickson/MTGO-Tracker#3]
I have a completely blank statistics window and no buttons. it means that I have to close the application and I cannot perform any analysis.
![Screenshot 2022-04-30 191631](https://user-images.githubusercontent.com/6192612/166103324-d5e8bacf-c100-4f4f-af17-bbe2184356dc.png)

I have included a wetransfer link because i cannot add the 90mb zip file to this forum its too large.

https://we.tl/t-Y5VFt8w1u2

**Comment by cderickson** [comment]
Hey Derek,
Thanks for the bug report and sharing your files with me. I believe I've found the issue and have uploaded an update that should fix it (https://github.com/cderickson/MTGO-Tracker/releases/tag/2022-v.3.2).

If you run into any other issues, please let know and I'll do my best to help you out.

![Capture11](https://user-images.githubusercontent.com/17014141/166108498-5181c698-c8d2-4c95-8158-09e270f542a1.PNG)
