### ISSUE TITLE
Unable to Update a field of many matches at once

### ISSUE THREAD

**Issue by stevenflo** [cderickson/MTGO-Tracker#4]
I recently downloaded and attempted to use the app. However, for my 300+ matches the format, event, and archetype columns are are unfilled causing data cleaning to be difficult for deck names. There should be a feature to update the format/event/archetype columns for 300+ matches at once.

**Comment by cderickson** [comment]
Hey Steven, if you multi-select multiple rows before clicking the Revise Record button, the change will be applied to each selected row. You won't be able to update all 300+ matches in one operation, but you can update 25-35 matches at once and save considerable time.

Let me know if you have any other questions

**Comment by stevenflo** [comment]
I will close the issue then, it would be a nice quality of life fix but now that I have my backlog updated, it is easy to add in new matches
