### ISSUE TITLE
Decklists are outdated and don't include ONE

### ISSUE THREAD

**Issue by stevenflo** [cderickson/MTGO-Tracker#5]
The current decklist data is from December and therefore no current games are getting proper decks assigned (for Pioneer at least). I would also be interested to see what the algorithm is for selecting the archetype and deck name.

**Comment by cderickson** [comment]
Both these files have been updated ([ALL_DECKS_2023-01](https://github.com/cderickson/MTGO-Tracker/raw/main/ALL_DECKS_2023-01), [INPUT_OPTIONS.txt](https://raw.githubusercontent.com/cderickson/MTGO-Tracker/main/INPUT_OPTIONS.txt)), just download and replace them. Apologies for not diligently updating these files, I'm working on porting this to a web app so users don't have to constantly update these files.

Best Guess Deck Naming Algorithm: 

- Scrape decklists monthly from MTGGoldfish.com and save sample decklists for recurring (2+ appearances) decks
- Compare a list of cards played by a player during a match
- Return the deck name of a sample decklist that contains the highest percentage of played cards

This is a pretty rudimentary process and accuracy depends on the number of cards played during a match. 
For example, I'll play Legacy matches against turn-1 combo decks where the only cards I play are Land + Force of Will, and it will return one of any number of decks. This is meant as a "first pass" step to use when importing a large number of new matches.
