### ISSUE TITLE
Fail to import Match Data

### ISSUE THREAD

**Issue by neoteroinvin** [cderickson/MTGO-Tracker#6]
Seeming to have an issue with importing match data after setting the gamelog folder and selecting either re-scan or re-import. As can be seen in the debug file, the program is properly placing the _.dat_ files into the programs copy directory, but doesn't seem to do anything with them afterwards. 

Most of the games are games of Modern, but I know some of them are commander games. Reading the comments of a post you did relatively recently on reddit, you mention that the tracker hadn't been tested for commander games, so I thought this might possibly be an issue. 

Unfortunately, I can recognize a few games and try and delete them from the folder but I'm not sure I got all of them to check if this was indeed the issue. Let me know if there is any other info I can provide. This is on the v4.0 tracker.

[DEBUG.txt](https://github.com/cderickson/MTGO-Tracker/files/11243063/DEBUG.txt)

**Comment by neoteroinvin** [comment]
Looking at the other closed issues, I've also attached a copy of my gamelogs folder as well to help with debugging.

[Match_GameLog_0771b675-4f90-4bc5-8f2e-44af38e34873.zip](https://github.com/cderickson/MTGO-Tracker/files/11243075/Match_GameLog_0771b675-4f90-4bc5-8f2e-44af38e34873.zip)

**Comment by cderickson** [comment]
Thanks for the report and uploading your GameLogs. If it's just an error trying to parse commander games, it should be an easy fix that I can implement by this weekend.

**Comment by cderickson** [comment]
These issues should be fixed now in the latest release and I was able to import your game logs on my system. Let me know if you run into any other problems.
